version: 2
registries:
  nvcr:
    type: docker-registry
    url: https://nvcr.io
    username: ${{secrets.NVCR_USERNAME}}
    password: ${{secrets.NVCR_TOKEN}}
updates:
  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - nvcr
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - nvcr
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    target-branch: network-operator-26.4.x
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - nvcr
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    target-branch: network-operator-26.7.x
