version: 2
registries:
  nvcr:
    type: docker-registry
    url: https://nvcr.io
    username: ${{secrets.NVCR_USERNAME}}
    password: ${{secrets.NVCR_TOKEN}}
updates:
  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - nvcr
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
