name: Reusable Fork Sync

on:
  workflow_call:
    inputs:
      default-branch:
        description: "Name of the default branch to sync"
        required: true
        type: string
      upstream-owner:
        description: "Owner of the upstream repo on Github"
        required: true
        type: string
      service-account-username:
        description: "Name of the GH service account to push changes"
        type: string
        required: false
      service-account-email:
        description: "E-mail, associated with the GH service account"
        type: string
        required: false 
    secrets:
      gh_token:
        description: "GH token for the CI/CD account"
        required: true

jobs:
  lookup-most-recent-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lookup most recent release branch
        id: lookup-most-recent-release-branch
        run: |
          git fetch --all
          echo most_recent_release_branch=$(git branch --remotes --sort refname | grep network-operator- | tail -n 1 | cut -d '/' -f 2-) >> $GITHUB_OUTPUT
    outputs:
      most_recent_release_branch: ${{ steps.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}

  sync-default-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync
        env:
          GH_TOKEN: ${{ secrets.gh_token }}  # classic personal access token permissions: `repo:*,workflow:*`
        run: |
          gh repo sync ${{ github.repository }} --source ${{ inputs.upstream-owner }}/${{ github.event.repository.name }} --branch ${{ inputs.default-branch }}

  sync-latest-release-branch:
    runs-on: ubuntu-latest
    needs: lookup-most-recent-release-branch
    if: ${{ needs.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}
          fetch-depth: 0
      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/${{ inputs.upstream-owner }}/${{ github.event.repository.name }}.git
          git fetch upstream ${{ inputs.default-branch }}
      - name: Rebase onto upstream branch
        run: |
          git config user.name ${{inputs.service-account-username || 'github-actions[bot]'}}
          git config user.email ${{inputs.service-account-email || 'github-actions[bot]@users.noreply.github.com'}}

          git rebase upstream/${{ inputs.default-branch }}
      - name: Push rebased branch
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          git push origin ${{ needs.lookup-most-recent-release-branch.outputs.most_recent_release_branch }} --force-with-lease

