# Copyright 2026 NVIDIA CORPORATION & AFFILIATES
# SPDX-License-Identifier: Apache-2.0

name: Test Component CI
on:
  pull_request:
    paths:
      - '.github/workflows/go-*-reusable.yml'
      - '.github/workflows/image-build-reusable.yml'
      - '.github/workflows/test-component-ci.yml'
      - 'tests/component-ci/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go-ci:
    uses: ./.github/workflows/go-ci-reusable.yml
    with:
      install-task: true
      build-command: |
        task --version
        cd tests/component-ci
        go build ./...
      lint-command: cd tests/component-ci && go vet ./...
      test-command: cd tests/component-ci && go test -race -coverprofile=cover.out ./...
      validate-command: |
        cd tests/component-ci
        go mod tidy
        git diff --exit-code
  image:
    uses: ./.github/workflows/image-build-reusable.yml
    with:
      context: tests/component-ci
      dockerfile: tests/component-ci/Dockerfile
      build-args: |
        MESSAGE=reusable-ci
